# Generated by Django 5.1.1 on 2025-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPWBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('beginning_battletime', models.DateField()),
                ('ending_battletime', models.DateField()),
                ('ussr_glavkom', models.CharField(max_length=255)),
                ('germ_glavkom', models.CharField(max_length=255)),
            ],
        ),
    ]
