# Generated by Django 5.1.1 on 2025-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpwbattle',
            name='beginning_battletime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gpwbattle',
            name='ending_battletime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gpwbattle',
            name='germ_glavkom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gpwbattle',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gpwbattle',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gpwbattle',
            name='ussr_glavkom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
