# Generated by Django 5.1.1 on 2025-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gpwbattle_beginning_battletime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpwbattle',
            name='description',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
